SLAP_GIFS = [
  
  "CgACAgQAAx0CZPMwOAABJTbpYsMTyA2yl0rAAq2b_a8yKV1qq3AAAlYDAALHqQVT4aQjEqxA-UgpBA",

"CgACAgQAAx0CZPMwOAABJTb3YsMUCrN81PucLK8THBJzPpS0agEAAj0DAAIa3gRTx3LMQydYoOspBA",

"CgACAgQAAx0CZPMwOAABJTb_YsMUPHpczgkgXV4o6gwFNU28rjQAAkMDAAJKFAVT_82kMSF3BHopBA",

"CgACAgQAAx0CZPMwOAABJTcGYsMUcrslrd75OIQwB2eJKVdrC9AAAgEDAAJuwQ1TejqVTYpsYWgpBA",

"CgACAgQAAx0CZPMwOAABJTcMYsMUoBFain9TWVc_2UkRKRISFG4AAjcDAAJwtQRTxn-k3IZefmYpBA",

"CgACAgQAAx0CZPMwOAABJTclYsMWdw8Uljz8ZNr-52xj7y8TxZ8AAuoCAAKD0QxT04TmilcEsVIpBA"

  ]

SLAP_TEXT = [

     "{user1} slapped {user2}"

   ]
